# Please re-run stencil after any changes to this file as invalid
# syntax, such as anchors, will be fixed automatically.
version: 2.1
orbs:
  shared: getoutreach/shared@dev:2.22.0-rc.2
  queue: eddiewebb/queue@2.2.1

parameters:
  rebuild_cache:
    type: boolean
    default: false

# Extra contexts to expose to all jobs below
contexts: &contexts
  - aws-credentials
  - ghaccesstoken
  - docker-registry
  - npm-credentials
  - vault-dev
  - confluence
  - circleci-credentials
  - tray-webhooks
  ## <<Stencil::Block(extraContexts)>>

  ## <</Stencil::Block>>

# Test configs to pass to test and cache jobs
test: &test
  context: *contexts
  app_name: suryaintro
  ### Start parameters inserted by other modules
  ### End parameters inserted by other modules
  ## <<Stencil::Block(circleTestExtra)>>

  ## <</Stencil::Block>>

# Branches used for releasing code, pre-release or not
release_branches: &release_branches
  - "main"

jobs:
  ## <<Stencil::Block(circleJobs)>>

  ## <</Stencil::Block>>

  ### Start jobs inserted by other modules
  deploy_image:
    executor:
      name: shared/testbed-docker
    steps:
      - queue/until_front_of_line:
          circleci-api-key: CIRCLECI_API_TOKEN
          only-on-branch: main
          time: "10"
      - shared/setup_environment
      - run:
          command: make deploy CHANNEL=ops
          name: Notify Maestro of Image Creation
  ### End jobs inserted by other modules

workflows:
  version: 2
  ## <<Stencil::Block(circleWorkflows)>>

  ## <</Stencil::Block>>

  ### Start workflows inserted by other modules
  ### End workflows inserted by other modules

  rebuild-cache:
    triggers:
      - schedule:
          # Every day at 00:00 UTC.
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - shared/save_cache: *test

  manual-rebuild-cache:
    when: << pipeline.parameters.rebuild_cache >>
    jobs:
      - shared/save_cache: *test

  release:
    when:
      not: << pipeline.parameters.rebuild_cache >>
    jobs:
      ## <<Stencil::Block(circleWorkflowJobs)>>

      ## <</Stencil::Block>>
      ### Start jobs inserted by other modules
      - deploy_image:
          context:
            - docker-registry
            - ghaccesstoken
            - circleci-credentials
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
          requires:
            - shared/test
            - shared/docker_stitch
      ### End jobs inserted by other modules
      - shared/release: &release
          dryrun: false
          context: *contexts
          ## <<Stencil::Block(circleReleaseExtra)>>

          ## <</Stencil::Block>>
          requires:
            ## <<Stencil::Block(circleReleaseRequires)>>

            ## <</Stencil::Block>>
            - shared/test
          filters:
            branches:
              only: *release_branches

      # Dryrun release for PRs.
      - shared/release:
          <<: *release
          dryrun: true
          filters:
            branches:
              ignore: *release_branches
      - shared/test:
          <<: *test
          ## <<Stencil::Block(circleSharedTestExtra)>>

          ## <</Stencil::Block>>
      - shared/publish_docs:
          context: *contexts
          filters:
            branches:
              only:
                - main
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
      - shared/e2e:
          context: *contexts
          ## <<Stencil::Block(circleE2EExtra)>>

          ## <</Stencil::Block>>
      - shared/docker_stitch:
          context: *contexts
          requires:
            - shared/docker_amd64
            - shared/docker_arm64
          filters:
            branches:
              ignore: *release_branches
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
      - shared/docker_amd64:
          context: *contexts
          filters:
            branches:
              ignore: *release_branches
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
      - shared/docker_arm64:
          context: *contexts
          filters:
            branches:
              ignore: *release_branches
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
